version: '3.8'

networks:
  traefik-public:
    external: true
  app-network:
    driver: bridge

services:
  # Base de datos PostgreSQL
  postgres:
    image: postgres:15
    container_name: ccjap-postgres
    restart: always
    environment:
      POSTGRES_USER: ccjap_admin
      POSTGRES_PASSWORD: K@rur0su24
      POSTGRES_DB: ccjap_db
    volumes:
      - ccjap_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # Backend API
  backend:
    image: node:18-alpine
    container_name: ccjap-backend
    restart: always
    working_dir: /app
    command: sh -c "npm install && npm start"
    volumes:
      - ./backend:/app
      - ccjap_uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ccjap_db
      - DB_USER=ccjap_admin
      - DB_PASSWORD=K@rur0su24
      - JWT_SECRET=K@rur0su24_JWT_SECRET_2025
      - UPLOAD_DIR=/app/uploads
    depends_on:
      - postgres
    networks:
      - app-network
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ccjap-backend.rule=Host(`api.ccjap.echolab.xyz`)"
      - "traefik.http.routers.ccjap-backend.entrypoints=websecure"
      - "traefik.http.routers.ccjap-backend.tls.certresolver=letsencrypt"
      - "traefik.http.services.ccjap-backend.loadbalancer.server.port=3001"

  # Frontend
  frontend:
    image: node:18-alpine
    container_name: ccjap-frontend
    working_dir: /app
    command: sh -c "npm install && npm run build && npx serve -s build -l 3000"
    volumes:
      - ./frontend:/app
    networks:
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ccjap-frontend.rule=Host(`ccjap.echolab.xyz`)"
      - "traefik.http.routers.ccjap-frontend.entrypoints=websecure"
      - "traefik.http.routers.ccjap-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.ccjap-frontend.loadbalancer.server.port=3000"

  # n8n
  n8n:
    image: n8nio/n8n
    container_name: ccjap-n8n
    restart: always
    environment:
      - N8N_HOST=n8n.echolab.xyz
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - N8N_HOST_WHITELIST=n8n.echolab.xyz
      - N8N_ENCRYPTION_KEY=K@rur0su24_N8N_ENCRYPT_2025
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=ccjap_admin
      - DB_POSTGRESDB_PASSWORD=K@rur0su24
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=K@rur0su24
    volumes:
      - ccjap_n8n_data:/home/node/.n8n
    networks:
      - traefik-public
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ccjap-n8n.rule=Host(`n8n.echolab.xyz`)"
      - "traefik.http.routers.ccjap-n8n.entrypoints=websecure"
      - "traefik.http.routers.ccjap-n8n.tls.certresolver=letsencrypt"
      - "traefik.http.services.ccjap-n8n.loadbalancer.server.port=5678"

volumes:
  ccjap_postgres_data:
    external: true
  ccjap_uploads:
    external: true
  ccjap_n8n_data:
    external: true